openapi: 3.0.0
info:
  title: API soporte técnico
  version: '1.0'
paths:
  //soporte:
    post:
      summary: Inserta una nueva petición a soporte tecnico
      tags: 
      - Soporte tecnico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id_usuario
                - descripcion_problema
                - fecha_problema
              properties:
                id_usuario:
                  type: integer
                descripcion_problema:
                  type: string
                fecha_problema:
                  type: string
            example:
              id_usuario: 001
              fecha_problema: "20/04/2022"
              descripcion_problema: "Problema con la aplicación movil"
      responses:
        '200':
            description: Peticion correcta
            content: 
              application/json:
                examples:
                  Insertar petición a soporte tecnico:
                    value:  >-
                        {
                          "id_usuario": "001",
                          "fecha_problema": "20/04/2022",
                          "descripcion_problema": "Problema con la aplicación móvil"
                        }
        '400':
            description: Peticion incorrecta
            content:
              application/json:
                examples:
                  Error al meter incidencia:
                    value: "{\"error\": \"Malformed request syntax.\"}"
              
    get:
      tags:
        - Soporte tecnico
      summary: "Encontrar el ticket/la peticion de soporte del usuario"
      responses:
        '200':
            description: Peticion correcta
            content: 
              application/json:
                examples:
                  Insertar petición a soporte tecnico:
                    value:  >-
                        {
                          "Usuario/cliente id": "0123456789",
                          "Descripción del problema": "No se porque no carga mi coche",
                          "Fecha": "01/02/20222",
                          "Estado": false,
                          "Registro de mensajes de chat": [ {
                              "Usuario emisor id": "0123456789",
                              "Mensaje": "No se porque no carga mi coche",
                              "Fecha" : "01/02/20222"
                            },
                            {
                              "Usuario emisor id": "000000111",
                              "Mensaje": "Hola Pablo, ¿ha provado de darle el boton verde?",
                              "Fecha" : "01/02/20222"
                            },
                            {
                              "Usuario emisor id": "0123456789",
                              "Mensaje": "¿Que boton verde? ¡Hay muchos y soy daltonico!",
                              "Fecha" : "01/02/20222"
                            }
                          ]
                        }
        '400':
            description: "Peticion incorrecta"
            content:
              application/json:
                examples:
                  Error al meter incidencia:
                    value: "{\"error\": \"ID ususario no valido.\"}"
        '404':
            description: "Peticion no encontrado"
            content:
              application/json:
                examples:
                  Error al meter incidencia:
                    value: "{\"error\": \"ID ususario no valido.\"}"
              
    delete:
      tags:
        - Soporte tecnico
      summary: "Eliminar un ticket/una peticion del soporte del usuario"
      responses:
        '200':
            description: Peticion correcta
            content: 
              application/json:
                examples:
                  Insertar petición a soporte tecnico:
                    value:  >-
                        {
                          "code": 200,
                          "id": "unknown",
                          "message": "1"
                        }
        '400':
            description: "Peticion incorrecta"
            content:
              application/json:
                examples:
                  Error al meter incidencia:
                    value: "{\"error\": \"ID ususario no valido.\"}"
        '404':
            description: "Peticion no encontrado"
            content:
              application/json:
                examples:
                  Error al meter incidencia:
                    value: "{\"error\": \"ID ususario no valido.\"}"
        '410':
            description: "Peticion no encontrado"
            content:
              application/json:
                examples:
                  Error al meter incidencia:
                    value: "{\"error\": \"ID ususario no valido.\"}"
