openapi: 3.0.0
info:
  title: API portal de gestion
  version: '1.0'
servers:
  - url: http://127.0.0.1:8080/
    description: Developments
  - url: http://craaxkvm.epsevg.upc.es:23701/
    description: Server
paths:
  # reservas
  /reservas:
    get:
      summary: Obtiene todas las reservas de todos los clientes (no me uses)
      tags:
        - Reservas
      responses:
          '200':
            description: Peticion correcta
            content:
              application/json:
                examples:
                  Meter reserva:
                    value:  >-
                        [
                          {
                            "fecha_entrada": "2022-04-18T11:00:00",
                            "fecha_salida": "2022-04-18T18:00:00",
                            "id_cargador": 1,
                            "id_cliente": "1238712N",
                            "id_reserva": 1,
                            "id_vehiculo": "LKE2378"
                          }
                        ]
          '400':
            description: Peticion incorrecta
            content:
              application/json:
                examples:
                  Error al meter reserva:
                    value: >-
                      {"error": "Malformed request syntax."}
                      
    # mandamos/resolvemos 1 reserva]
    post:
      summary: Inserta una nueva reserva
      tags:
      - Reservas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                  - id_estacion
                  - fecha_inicio
                  - fecha_final
                  - id_vehiculo
                  - id_cliente
              properties:
                id_estacion:
                  type: integer
                fecha_inicio:
                  type: string
                fecha_final:
                  type: string
                id_vehiculo:
                  type: string
                id_cliente:
                  type: string
              example:
                id_estacion: 1
                fecha_inicio: "18-04-2022 11:00"
                fecha_final: "18-04-2022 18:00"
                id_vehiculo: "LKE2378"
                id_cliente: "1238712N"
      responses:
        '200':
          description: Peticion correcta
          content:
            application/json:
              examples:
                Meter reserva:
                  value:  >-
                      {
                        "id_cliente": "1238712N",
                        "fecha_entrada": "2022-04-18T18:00:00",
                        "fecha_salida": "2022-04-18T11:00:00",
                        "id_reserva": 1,
                        "id_estacion": 1,
                        "id_vehiculo": "LKE2378",
                        "id_cargador": 2
                      }
        '400':
          description: Peticion incorrecta
          content:
            application/json:
              examples:
                Error al meter reserva:
                  value: >-
                    {"error": "Malformed request syntax."}

  /reservas/estacion/{id_estacion}:
    # pedimos una lista de reservas por una estacion dada
    get:
      summary: Obtiene una lista de reservas para una estacion dada obtiene solo las reservas desde ahora al futuro
      tags:
      - Reservas
      parameters:
        - in: path
          name: id_estacion
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Obtiene un lista de reservas por estacion desde la fecha actual al futuro
          content:
            application/json:
              examples:
                Con reservas:
                  value: >-
                        [
                          {
                            "fecha_entrada": "2022-07-18T11:00:00",
                            "fecha_salida": "2022-07-18T18:00:00",
                            "id_cargador": 1,
                            "id_cliente": "1238712N",
                            "id_reserva": 1,
                            "id_vehiculo": "LKE2378"
                          },
                          {
                            "fecha_entrada": "2022-07-18T12:00:00",
                            "fecha_salida": "2022-07-18T115:00:00",
                            "id_cargador": 2,
                            "id_cliente": "1238712N",
                            "id_reserva": 2,
                            "id_vehiculo": "LKE2378"
                          }
                        ]
                Sin reservas:
                  value: '[]'
        '401':
          description: Not login
          content:
            application/json:
              examples:
                error:
                  value: >-
                    {"error": "User not authenticated."}
  /reservas/bydni/{dni}:
    # pedimos una lista de reservas por un dni dado
    get:
      summary: Obtiene una lista de reservas para un dni dado
      tags:
      - Reservas
      parameters:
        - in: path
          name: dni
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Obtiene un lista de reservas
          content:
            application/json:
              examples:
                Con reservas:
                  value: >-
                        [
                          {
                            "fecha_entrada": "2022-07-18T11:00:00",
                            "fecha_salida": "2022-07-18T18:00:00",
                            "id_cargador": 1,
                            "id_cliente": "1238712N",
                            "id_reserva": 1,
                            "id_vehiculo": "LKE2378"
                          },
                          {
                            "fecha_entrada": "2022-07-18T12:00:00",
                            "fecha_salida": "2022-07-18T115:00:00",
                            "id_cargador": 2,
                            "id_cliente": "1238712N",
                            "id_reserva": 2,
                            "id_vehiculo": "LKE2378"
                          }
                        ]
                Sin reservas:
                  value: '[]'
        '401':
          description: Not login
          content:
            application/json:
              examples:
                error:
                  value: >-
                    {"error": "User not authenticated."}
  /reservas/bymatricula/{matricula}:
    # pedimos una lista de reservas por una matriculña dada
    get:
      summary: Obtiene una lista de reservas para una matricula dada
      tags:
      - Reservas
      parameters:
        - in: path
          name: matricula
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Obtiene un lista de reservas
          content:
            application/json:
              examples:
                Con reservas:
                  value: >-
                        [
                          {
                            "fecha_entrada": "2022-07-18T11:00:00",
                            "fecha_salida": "2022-07-18T18:00:00",
                            "id_cargador": 1,
                            "id_cliente": "1238712N",
                            "id_reserva": 1,
                            "id_vehiculo": "LKE2378"
                          },
                          {
                            "fecha_entrada": "2022-07-18T12:00:00",
                            "fecha_salida": "2022-07-18T115:00:00",
                            "id_cargador": 2,
                            "id_cliente": "1238712N",
                            "id_reserva": 2,
                            "id_vehiculo": "LKE2378"
                          }
                        ]
                Sin reservas:
                  value: '[]'
        '401':
          description: Not login
          content:
            application/json:
              examples:
                error:
                  value: >-
                    {"error": "User not authenticated."}
  /reservas/{id}:
      # pedimos una reserva, dado su id
      get:
        summary: Obtiene una reserva por un id dado
        tags:
          - Reservas
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: Default error sample response
            content:
              application/json:
                examples:
                  Reservas:
                    value:  >-
                        {
                          "fecha_entrada": "2022-04-18T11:00:00",
                          "fecha_salida": "2022-04-18T18:00:00",
                          "id_cargador": 1,
                          "id_cliente": "1238712N",
                          "id_reserva": 1,
                          "id_vehiculo": "LKE2378"
                        }
          '401':
            description: Not login
            content:
              application/json:
                examples:
                  error:
                    value: >-
                        {"error": "User not authenticated."}

          '404':
            description: Not found
            content:
              application/json:
                examples:
                  error:
                    value: >-
                        {"error": "Reserva not found."}

      #borrar reserva
      delete:
        summary: Elimina reserva por ID
        tags:
          - Reservas
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: Eliminado delete
            content:
              application/json:
                examples:
                  Reservas:
                    value: {"msg": "Data deleted correctly."}
                  Reserva no encontrada:
                    value: '[]'
          '401':
            description: Not login
            content:
              application/json:
                examples:
                  error:
                    value: >-
                      {"error": "User not authenticated."}
          '404':
            description: Not Found
            content:
              application/json:
                examples:
                  error:
                    value: >-
                      {"error": "Reserva not found."}

#########################################################################################
# clientes
  /clientes:
    # pedimos una lista de las incidencias
    get:
      summary: Obtiene una lista de clientes
      tags:
      - Clientes
      responses:
        '200':
          description: Peticion correcta
          content:
            application/json:
              examples:
                Con clientes:
                  value: [
                          {
                            "id_cliente": 1,
                            "nombre": "Pablo",
                            "apellido": "Escobar",
                            "email": "pablo@gmail.com",
                            "DNI": "23769543B",
                            "foto": "http://?????????/clientes/pablo.png",
                            "telefono": "643876101",
                            "username": "xXpabloXx",
                          },
                          {
                            "id_cliente": 2,
                            "nombre": "Javier",
                            "apellido": "Sanchez",
                            "email": "javi@gmail.com",
                            "DNI": "23769612h",
                            "foto": "http://?????????/clientes/javi.png",
                            "telefono": "643876101",
                            "username": "xXpabloXx",
                          }
                        ]

                Sin clientes:
                  value: '[]'
        '401':
          description: Not login
          content:
            application/json:
              examples:
                error:
                  value: >-
                    {"error": "User not authenticated."}
    post:
        summary: Inserta un nuevo cliente
        tags:
        - Clientes
        requestBody:
            required: true
            content:
              multipart/form-data:
                schema:
                  type: object
                  required:
                    - nombre
                    - apellido
                    - email
                    - DNI
                    - foto
                    - telefono
                    - username
                  properties:
                    nombre:
                      type: string
                    apellido:
                      type: string
                    email:
                      type: string
                    DNI:
                      type: string
                    foto:
                      type: string
                    telefono:
                      type: string
                    username:
                      type: string
                    #profileImage:
                    #  type: string
                    #  format: binary

                  example:
                    name: "Pere"
                    lastname: "Roca"
                    telf: "622554433"
                    email: "pere.roca@boss.com"
                    rol: "Dueño"
                    password: "proca"
        responses:
          '200':
            description: Peticion correcta
            content:
              application/json:
                examples:
                  Meter cliente:
                    value: [
                      {
                        "id_cliente": 1,
                        "nombre": "Pablo",
                        "apellido": "Escobar",
                        "email": "pablo@gmail.com",
                        "DNI": "23769543B",
                        "foto": "http://?????????/clientes/pablo.png",
                        "telefono": "643876101",
                        "username": "xXpabloXx",
                      },
                      ]
          '400':
              description: Peticion incorrecta
              content:
                application/json:
                  examples:
                    Error al meter incidencia:
                      value: {"error": "Malformed request syntax."}

          '401':
              description: Not login
              content:
                application/json:
                  examples:
                    error:
                      value: >-
                        {"error": "User not authorized."}
  /clientes/bydni/{DNI}:
    # pedimos un cliente dado su id
    get:
      summary: Obtiene un cliente dado su DNI
      tags:
        - Clientes
      parameters:
        - in: path
          name: DNI
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Default error sample response
          content:
            application/json:
              examples:
                Cliente encontrado:
                  value:
                      [
                        {
                          "id_cliente": 1,
                          "nombre": "Pablo",
                          "apellido": "Escobar",
                          "email": "pablo@gmail.com",
                          "DNI": "23769543B",
                          "foto": "http://?????????/clientes/pablo.png",
                          "telefono": "643876101",
                          "username": "xXpabloXx",
                        }
                      ]
                Cliente no encontrado:
                  value: '[]'
        '401':
          description: Not login
          content:
            application/json:
              examples:
                error:
                  value: >-
                      {"error": "User not authenticated."}
        '404':
          description: Not found
          content:
            application/json:
              examples:
                error:
                  value: >-
                      {"error": "Client not found."}
    # modificar cliente de la lista de clientes
    put:
        summary: Modifica un trabajador
        tags:
          - Clientes
        parameters:
        - in: path
          name: DNI
          required: true
          schema:
            type: string
        requestBody:
          required: true
          content:
            multipart/form-data:
              schema:
                  type: object
                  required:
                    - nombre
                    - apellido
                    - email
                    - DNI
                    - foto
                    - telefono
                    - username
                  properties:
                    nombre:
                      type: string
                    apellido:
                      type: string
                    email:
                      type: string
                    DNI:
                      type: string
                    foto:
                      type: string
                    telefono:
                      type: string
                    username:
                      type: string
                    #profileImage:
                    #  type: string
                    #  format: binary
        responses:
          '200':
            description: Peticion correcta
            content:
              application/json:
                examples:
                  Trabajador actualizado:
                    value: >-
                          {
                            "id_cliente": 2,
                            "nombre": "Javier",
                            "apellido": "Sanchez",
                            "email": "javi@gmail.com",
                            "DNI": "23769612h",
                            "foto": "http://?????????/clientes/javi.png",
                            "telefono": "643876101",
                            "username": "xXpabloXx",
                          }
          '400':
            description: Peticion incorrecta
            content:
              application/json:
                examples:
                  Error al meter cliente:
                    value: {"error": "Malformed request syntax."}
          '404':
            description: Not Found
            content:
              application/json:
                examples:
                  error:
                    value: {"error": "User not found."}
  
  #borrar cliente
  
    delete:
      summary: Elimina cliente por id
      tags:
        - Clientes
      parameters:
        - in: path
          name: DNI
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cliente eliminado delete
          content:
            application/json:
              examples:
                Incidencias:
                  value: {"msg": "User deleted correctly."}
                Incidencia no encontrada:
                  value: '[]'
        '401':
          description: Not login
          content:
            application/json:
              examples:
                error:
                  value: >-
                    {"error": "User not authenticated."}
        '404':
          description: Not Found
          content:
            application/json:
              examples:
                error:
                  value: >-
                    {"error": "User not found."}
#######################################################################################################

